# Generated by Django 2.2.4 on 2019-08-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteagency',
            name='from_date',
            field=models.DateField(verbose_name='agency from date'),
        ),
        migrations.AlterField(
            model_name='siteagency',
            name='to_date',
            field=models.DateField(blank=True, verbose_name='agency to date'),
        ),
        migrations.AlterField(
            model_name='siteoperation',
            name='from_date',
            field=models.DateField(verbose_name='operational from date'),
        ),
        migrations.AlterField(
            model_name='siteoperation',
            name='to_date',
            field=models.DateField(blank=True, verbose_name='operational to date'),
        ),
    ]
