# Generated by Django 2.2.4 on 2019-08-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20190829_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteagency',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='agency to date'),
        ),
        migrations.AlterField(
            model_name='siteoperation',
            name='to_date',
            field=models.DateField(blank=True, null=True, verbose_name='operational to date'),
        ),
    ]
