# Generated by Django 2.2.4 on 2019-10-12 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20191013_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteagency',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_to_site', to='sites.Agency'),
        ),
        migrations.AlterField(
            model_name='siteagency',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_to_agency', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='siteidentifiers',
            name='identifier_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ident_type_to_site', to='sites.IdentifierType'),
        ),
        migrations.AlterField(
            model_name='siteidentifiers',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_to_ident_type', to='sites.Site'),
        ),
    ]
