# Generated by Django 2.2.4 on 2019-10-13 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_auto_20191013_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteagency',
            name='agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_to_site', to='sites.Agency'),
        ),
    ]
