# Generated by Django 2.2.4 on 2019-10-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0014_auto_20191013_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteServiceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AgencySiteListServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_url', models.CharField(max_length=250)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Agency')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_service_types', to='sites.SiteServiceTypes')),
            ],
        ),
        migrations.AddField(
            model_name='agency',
            name='site_webservices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_site_lists', to='sites.AgencySiteListServices'),
        ),
    ]
