# Generated by Django 2.2.4 on 2019-09-09 20:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20190829_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='site location'),
        ),
    ]
