# Generated by Django 2.2.4 on 2019-10-12 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20191013_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteidentifiers',
            name='identifier_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_ident', to='sites.IdentifierType'),
        ),
        migrations.AlterField(
            model_name='siteidentifiers',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_ident', to='sites.Site'),
        ),
    ]
