# Generated by Django 2.2.4 on 2019-10-13 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_auto_20191013_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteidentifiers',
            name='identifier_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.IdentifierType'),
        ),
    ]
