# Generated by Django 2.2.4 on 2019-10-12 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_site_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='agencies',
            field=models.ManyToManyField(through='sites.SiteAgency', to='sites.Agency'),
        ),
        migrations.AddField(
            model_name='site',
            name='identifiers',
            field=models.ManyToManyField(through='sites.SiteIdentifiers', to='sites.IdentifierType'),
        ),
    ]
