# Generated by Django 2.2.4 on 2019-10-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20191012_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteagency',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_date', to='sites.Agency'),
        ),
        migrations.AlterField(
            model_name='siteidentifiers',
            name='identifier_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifier', to='sites.IdentifierType'),
        ),
    ]
