# Generated by Django 2.2.4 on 2019-10-13 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_auto_20191013_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteagency',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_agencies', to='sites.Site'),
        ),
    ]
