# Generated by Django 2.2.4 on 2019-10-28 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0016_about_aboutbody_apiconformance_apiinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='body',
        ),
        migrations.AddField(
            model_name='aboutbody',
            name='about',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_body', to='sites.About'),
        ),
    ]
