# Generated by Django 2.2.6 on 2019-11-06 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0018_auto_20191031_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='site_webservices',
        ),
        migrations.DeleteModel(
            name='AgencySiteListServices',
        ),
    ]
