# Generated by Django 2.2.6 on 2019-11-06 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0019_auto_20191106_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='agencies',
            field=models.ManyToManyField(null=True, through='sites.SiteAgency', to='sites.Agency'),
        ),
        migrations.AlterField(
            model_name='site',
            name='identifiers',
            field=models.ManyToManyField(null=True, through='sites.SiteIdentifiers', to='sites.IdentifierType'),
        ),
        migrations.AlterField(
            model_name='siteagency',
            name='agency',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_to_site', to='sites.Agency'),
        ),
        migrations.AlterField(
            model_name='siteidentifiers',
            name='identifier_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ident_site', to='sites.IdentifierType'),
        ),
        migrations.AlterField(
            model_name='siteoperation',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sites.Site'),
        ),
    ]
