# Generated by Django 2.2.6 on 2019-11-07 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0020_auto_20191106_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteagency',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_to_site', to='sites.Agency'),
        ),
        migrations.AlterField(
            model_name='siteidentifiers',
            name='identifier_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_ident', to='sites.IdentifierType'),
        ),
    ]
