# Generated by Django 2.2.6 on 2019-11-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0021_auto_20191107_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteagency',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Agency'),
        ),
        migrations.AlterField(
            model_name='siteagency',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='siteidentifiers',
            name='identifier_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.IdentifierType'),
        ),
        migrations.AlterField(
            model_name='siteidentifiers',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
