# Generated by Django 2.2.6 on 2019-11-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0022_auto_20191110_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='identifiertype',
            name='identifier_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
