# Generated by Django 2.2.6 on 2019-11-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0023_auto_20191111_2034'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='siteidentifiers',
            constraint=models.UniqueConstraint(fields=('identifier_type', 'identifier'), name='unique other identifiers'),
        ),
    ]
