# Generated by Django 2.2.6 on 2019-11-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0024_auto_20191111_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['pk']},
        ),
    ]
