# Generated by Django 2.2.6 on 2019-11-21 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0026_auto_20191122_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCollections',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('api_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.ApiInfo')),
            ],
        ),
    ]
