# Generated by Django 2.2.6 on 2019-11-22 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0027_apicollections'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconformance',
            name='api_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.ApiInfo'),
        ),
    ]
