# Generated by Django 2.2.6 on 2019-11-30 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0028_apiconformance_api_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteOperation',
        ),
    ]
