# Generated by Django 2.2.6 on 2019-11-30 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0031_auto_20191201_1053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteAgencyMeasurements',
            new_name='SiteAgencyMeasurement',
        ),
    ]
