# Generated by Django 2.2.6 on 2019-11-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0032_auto_20191201_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observedproperty',
            name='observed_property_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
