# Generated by Django 2.2.6 on 2019-12-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0033_auto_20191201_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteagencymeasurement',
            old_name='meas_from',
            new_name='observed_from',
        ),
        migrations.RenameField(
            model_name='siteagencymeasurement',
            old_name='meas_to',
            new_name='observed_to',
        ),
        migrations.AddField(
            model_name='agencymeasurement',
            name='measurement_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
