# Generated by Django 2.2.6 on 2019-12-04 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0034_auto_20191204_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterpolationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpolation_type_name', models.CharField(max_length=200, unique=True)),
                ('interpolation_type_url', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='agencymeasurement',
            name='interpolation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.InterpolationType'),
        ),
    ]
